### PR TITLE
[spatialPartitioning] Set kdtree buffer size after container conversion

### LINKED ISSUE #305: Regression with point container type applications
The following code from Poncascope doesn't work anymore with latest release
```
template<typename KdTreeType>
void buildKdTree(const Eigen::MatrixXd& cloudV, const Eigen::MatrixXd& cloudN, KdTreeType& tree){
    std::vector<int> ids(cloudV.rows());
    std::iota(ids.begin(), ids.end(), 0);

    using VN = std::pair<const Eigen::MatrixXd&, const Eigen::MatrixXd&>;

    // Build KdTree: do not copy coordinate but rather store Eigen::Block
    tree.buildWithSampling(VN(cloudV, cloudN),
                           ids,
                           [](VN bufs, typename KdTreeType::PointContainer &out) {
                               int s = bufs.first.rows();
                               out.reserve(s);
                               for (int i = 0; i != s; ++i)
                                   out.push_back(typename KdTreeType::DataPoint(bufs.first.row(i).transpose(),
                                                                                bufs.second.row(i).transpose()));
                           });
}
```

This is caused by the change made in `KdTreeBase<Traits>::buildWithSampling`, where we now call `points.size()` to initialize the `Base::m_bufs.points_size` value, which isn't available with `std::pair`. 

# Suggested change

We should fetch the size value after converting the container to its internal type (of `std::vector`). We won't be calling this function on internal pointer type anyway, since `KdTreeBase` methods are only defined for containers that are STL-like.

### PR DESCRIPTION
**Pull request by Me-k-01**
- Fix regression #305 by setting the buffer size after the container conversion
- Avoid Forwarding reference warning

### CODE REVIEW

File: Ponca/src/SpatialPartitioning/KdTree/kdTree.hpp [hunk 1]
```diff
@@ -123,10 +123,10 @@ PONCA_MULTIARCH_HOST inline void KdTreeBase<Traits>::buildWithSampling(PointUser
 
     // Move, copy or convert input samples
     c(std::forward<PointUserContainer>(points), Base::m_bufs.points);
-    Base::m_bufs.points_size = points.size();
+    Base::m_bufs.points_size = Base::m_bufs.points.size();
 
-    Base::m_bufs.indices_size = sampling.size();
-    Base::m_bufs.indices      = std::move(sampling);
+    Base::m_bufs.indices      = std::forward<IndexUserContainer>(sampling);
```
Comment (nmellado) [inline Ponca/src/SpatialPartitioning/KdTree/kdTree.hpp:128]: This PR adds two changes : 
- calling `.size()` on the STL container (instead of the custom one)
- replacing a `move` by a forward.

I got the rational for the first change (#305), but not for the second one. Could you please elaborate ?

Comment (Me-k-01) [reply Ponca/src/SpatialPartitioning/KdTree/kdTree.hpp:128]: Using Clion I was getting the following warning with `std::move` : 

```
Clang-Tidy: Forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead 
```

If it's irrelevant I can change it back to `std::move`

Comment (nmellado) [reply Ponca/src/SpatialPartitioning/KdTree/kdTree.hpp:128]: it's ok, just wanted to have the rationale.

**Review by nmellado — APPROVED** [review]
